import React, { useState } from 'react';
import {
    View,
    Text,
    ScrollView,
    SafeAreaView,
    Pressable,
    ActivityIndicator,
    useColorScheme,
    Alert,
} from 'react-native';
import * as Clipboard from 'expo-clipboard';
import {
    ArrowLeft,
    UserPlus,
    Copy,
    Check,
    Coins,
    Users,
    DollarSign,
    Clock,
} from 'lucide-react-native';
import { useWallet } from '../providers';
import { useReferralStats, useGenerateReferralCode, useClaimReferral } from '../hooks/use-referral';

const formatUSDC = (amount: number) => (amount / 1_000_000).toFixed(2);

export default function ReferralScreen({ navigation }: any) {
    const colorScheme = useColorScheme();
    const isDark = colorScheme === 'dark';
    const { connected, address } = useWallet();

    const { stats, isLoading, refetch } = useReferralStats();
    const { generateCode, isGenerating } = useGenerateReferralCode();
    const { claimReferral, isClaiming } = useClaimReferral();

    const [copied, setCopied] = useState(false);
    const [claimMessage, setClaimMessage] = useState<string | null>(null);

    const canClaim = (stats?.claimableAmount || 0) >= 5_000_000;

    const handleCopyLink = async () => {
        if (!stats?.referralLink) return;
        await Clipboard.setStringAsync(stats.referralLink);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleGenerate = async () => {
        setClaimMessage(null);
        try {
            await generateCode();
            await refetch();
        } catch (err: any) {
            Alert.alert('Error', err.message || 'Failed to generate code');
        }
    };

    const handleClaim = async () => {
        setClaimMessage(null);
        try {
            const data = await claimReferral();
            setClaimMessage(`Claimed $${data.amountUSDC.toFixed(2)}!`);
            await refetch();
        } catch (err: any) {
            setClaimMessage(err.message || 'Failed to claim');
        }
    };

    if (!connected) {
        return (
            <SafeAreaView className={`flex-1 ${isDark ? 'bg-slate-900' : 'bg-slate-50'}`}>
                <View className={`flex-row items-center px-4 py-3 ${isDark ? 'bg-slate-800 border-b border-slate-700' : 'bg-white border-b border-slate-100'}`}>
                    <Pressable onPress={() => navigation.goBack()} className="mr-3 p-1">
                        <ArrowLeft size={22} color={isDark ? '#f1f5f9' : '#1e293b'} />
                    </Pressable>
                    <Text className={`text-xl font-bold ${isDark ? 'text-slate-100' : 'text-slate-800'}`}>
                        Referral Program
                    </Text>
                </View>
                <View className="flex-1 items-center justify-center px-8">
                    <UserPlus size={48} color={isDark ? '#64748b' : '#94a3b8'} />
                    <Text className={`text-lg font-bold mt-4 text-center ${isDark ? 'text-slate-200' : 'text-slate-700'}`}>
                        Connect your wallet to access the referral program
                    </Text>
                </View>
            </SafeAreaView>
        );
    }

    return (
        <SafeAreaView className={`flex-1 ${isDark ? 'bg-slate-900' : 'bg-slate-50'}`}>
            {/* Header */}
            <View className={`px-4 py-3 ${isDark ? 'bg-slate-800 border-b border-slate-700' : 'bg-white border-b border-slate-100'}`}>
                <View className="flex-row items-center">
                    <Pressable onPress={() => navigation.goBack()} className="mr-3 p-1">
                        <ArrowLeft size={22} color={isDark ? '#f1f5f9' : '#1e293b'} />
                    </Pressable>
                    <View>
                        <Text className={`text-xl font-bold ${isDark ? 'text-slate-100' : 'text-slate-800'}`}>
                            Referral Program
                        </Text>
                        <Text className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                            Share the game, earn USDC
                        </Text>
                    </View>
                </View>
            </View>

            <ScrollView className="flex-1" showsVerticalScrollIndicator={false}>
                <View className="px-4 py-4">

                    {/* Commission Banner */}
                    <View className="bg-indigo-600 rounded-2xl p-5 mb-4">
                        <View className="flex-row items-center mb-2">
                            <DollarSign size={20} color="#fff" />
                            <Text className="text-white font-bold text-lg ml-1">20% Commission</Text>
                        </View>
                        <Text className="text-indigo-200 text-sm leading-5">
                            Earn 20% of the platform fees generated by every player you invite. Paid in USDC, lifetime.
                        </Text>
                    </View>

                    {isLoading ? (
                        <View className="py-12 items-center">
                            <ActivityIndicator size="large" color={isDark ? '#818cf8' : '#6366f1'} />
                        </View>
                    ) : (
                        <>
                            {/* Referral Link */}
                            <View className={`rounded-2xl overflow-hidden mb-4 ${isDark ? 'bg-slate-800' : 'bg-white'}`}>
                                <View className={`px-4 py-3 ${isDark ? 'border-b border-slate-700' : 'border-b border-slate-100'}`}>
                                    <Text className={`font-bold ${isDark ? 'text-slate-200' : 'text-slate-700'}`}>
                                        Your Referral Link
                                    </Text>
                                </View>
                                <View className="px-4 py-3">
                                    {stats?.code ? (
                                        <Pressable
                                            onPress={handleCopyLink}
                                            className={`flex-row items-center rounded-xl p-3 ${isDark ? 'bg-slate-700 active:bg-slate-600' : 'bg-slate-50 active:bg-slate-100'}`}
                                        >
                                            <Text
                                                className={`flex-1 font-mono text-xs mr-2 ${isDark ? 'text-slate-300' : 'text-slate-600'}`}
                                                numberOfLines={1}
                                            >
                                                {stats.referralLink}
                                            </Text>
                                            {copied ? (
                                                <Check size={18} color="#10b981" />
                                            ) : (
                                                <Copy size={18} color={isDark ? '#64748b' : '#94a3b8'} />
                                            )}
                                        </Pressable>
                                    ) : (
                                        <Pressable
                                            onPress={handleGenerate}
                                            disabled={isGenerating}
                                            className={`flex-row items-center justify-center rounded-xl p-3 border border-dashed ${isDark
                                                ? 'border-slate-600 active:bg-slate-700'
                                                : 'border-slate-300 active:bg-slate-50'
                                                } ${isGenerating ? 'opacity-50' : ''}`}
                                        >
                                            {isGenerating ? (
                                                <ActivityIndicator size="small" color={isDark ? '#818cf8' : '#6366f1'} />
                                            ) : (
                                                <>
                                                    <Coins size={16} color={isDark ? '#818cf8' : '#6366f1'} />
                                                    <Text className={`ml-2 font-medium text-sm ${isDark ? 'text-indigo-400' : 'text-indigo-600'}`}>
                                                        Generate Referral Link
                                                    </Text>
                                                </>
                                            )}
                                        </Pressable>
                                    )}
                                    {copied && (
                                        <Text className="text-emerald-500 text-xs mt-2 text-center font-medium">
                                            Copied to clipboard!
                                        </Text>
                                    )}
                                </View>
                            </View>

                            {/* Stats */}
                            <View className="flex-row gap-3 mb-4">
                                <View className={`flex-1 items-center p-4 rounded-xl ${isDark ? 'bg-slate-800' : 'bg-white'}`}>
                                    <Users size={18} color="#3b82f6" />
                                    <Text className="text-xl font-black text-blue-500 mt-1">
                                        {stats?.referralCount || 0}
                                    </Text>
                                    <Text className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                                        Referrals
                                    </Text>
                                </View>
                                <View className={`flex-1 items-center p-4 rounded-xl ${isDark ? 'bg-slate-800' : 'bg-white'}`}>
                                    <DollarSign size={18} color="#10b981" />
                                    <Text className="text-xl font-black text-emerald-500 mt-1">
                                        ${formatUSDC(stats?.lifetimeEarnings || 0)}
                                    </Text>
                                    <Text className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                                        Lifetime
                                    </Text>
                                </View>
                                <View className={`flex-1 items-center p-4 rounded-xl ${isDark ? 'bg-slate-800' : 'bg-white'}`}>
                                    <Coins size={18} color="#f59e0b" />
                                    <Text className="text-xl font-black text-amber-500 mt-1">
                                        ${formatUSDC(stats?.claimableAmount || 0)}
                                    </Text>
                                    <Text className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                                        Claimable
                                    </Text>
                                </View>
                            </View>

                            {/* Claim Button */}
                            <Pressable
                                onPress={handleClaim}
                                disabled={isClaiming || !canClaim}
                                className={`rounded-2xl p-4 mb-4 items-center ${canClaim
                                    ? 'bg-emerald-600 active:bg-emerald-700'
                                    : isDark ? 'bg-slate-800' : 'bg-slate-200'
                                    } ${(isClaiming || !canClaim) ? 'opacity-60' : ''}`}
                            >
                                {isClaiming ? (
                                    <ActivityIndicator size="small" color="#fff" />
                                ) : (
                                    <Text className={`font-bold text-base ${canClaim ? 'text-white' : (isDark ? 'text-slate-500' : 'text-slate-400')}`}>
                                        {canClaim
                                            ? `Claim $${formatUSDC(stats?.claimableAmount || 0)} USDC`
                                            : 'Minimum $5.00 to claim'}
                                    </Text>
                                )}
                            </Pressable>

                            {claimMessage && (
                                <Text className={`text-sm text-center mb-4 font-medium ${claimMessage.includes('Failed') || claimMessage.includes('failed')
                                    ? 'text-red-500'
                                    : 'text-emerald-500'
                                    }`}>
                                    {claimMessage}
                                </Text>
                            )}

                            {/* Recent Earnings */}
                            {stats?.recentEarnings && stats.recentEarnings.length > 0 && (
                                <View className={`rounded-2xl overflow-hidden mb-4 ${isDark ? 'bg-slate-800' : 'bg-white'}`}>
                                    <View className={`flex-row items-center px-4 py-3 ${isDark ? 'border-b border-slate-700' : 'border-b border-slate-100'}`}>
                                        <Clock size={16} color={isDark ? '#64748b' : '#94a3b8'} />
                                        <Text className={`ml-2 font-bold ${isDark ? 'text-slate-200' : 'text-slate-700'}`}>
                                            Recent Earnings
                                        </Text>
                                    </View>
                                    {stats.recentEarnings.map((earning, i) => (
                                        <View
                                            key={i}
                                            className={`flex-row items-center justify-between px-4 py-3 ${isDark ? 'border-b border-slate-700/50' : 'border-b border-slate-50'}`}
                                        >
                                            <View>
                                                <Text className={`text-xs font-mono ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
                                                    {earning.referee_wallet.slice(0, 4)}...{earning.referee_wallet.slice(-4)}
                                                </Text>
                                                <Text className={`text-[10px] ${isDark ? 'text-slate-500' : 'text-slate-400'}`}>
                                                    {new Date(earning.created_at).toLocaleDateString()}
                                                </Text>
                                            </View>
                                            <Text className="text-sm font-bold text-emerald-500">
                                                +${formatUSDC(earning.referral_commission)}
                                            </Text>
                                        </View>
                                    ))}
                                </View>
                            )}

                            {/* How It Works */}
                            <View className={`rounded-2xl overflow-hidden ${isDark ? 'bg-slate-800' : 'bg-white'}`}>
                                <View className={`px-4 py-3 ${isDark ? 'border-b border-slate-700' : 'border-b border-slate-100'}`}>
                                    <Text className={`font-bold ${isDark ? 'text-slate-200' : 'text-slate-700'}`}>
                                        How It Works
                                    </Text>
                                </View>
                                <View className="px-4 py-3">
                                    {[
                                        { step: '1', text: 'Share your unique referral link with friends' },
                                        { step: '2', text: 'They sign up and start playing Voble' },
                                        { step: '3', text: 'You earn 20% of platform fees from their games' },
                                        { step: '4', text: 'Claim your USDC earnings when balance reaches $5' },
                                    ].map((item) => (
                                        <View key={item.step} className="flex-row items-start mb-3">
                                            <View className={`w-6 h-6 rounded-full items-center justify-center mr-3 ${isDark ? 'bg-indigo-900/40' : 'bg-indigo-50'}`}>
                                                <Text className={`text-xs font-bold ${isDark ? 'text-indigo-400' : 'text-indigo-600'}`}>
                                                    {item.step}
                                                </Text>
                                            </View>
                                            <Text className={`flex-1 text-sm ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
                                                {item.text}
                                            </Text>
                                        </View>
                                    ))}
                                </View>
                            </View>
                        </>
                    )}

                    <View className="h-8" />
                </View>
            </ScrollView>
        </SafeAreaView>
    );
}
